### PR TITLE
Updated Vault repo url

### PR DESCRIPTION
**Pull request by MelonCode**

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Why bother, that url changes every 3 seconds...

**Comment by MelonCode** [comment]
To not make everybody who clones it fix it manually ¯\_(ツ)_/¯

**Comment by mcmonkey4eva** [comment]
I mean if you fix it now, it'll unfix itself in a few weeks when they change the URL to it for the millionth time over...

I have a better idea to solve this problem actually

**Comment by mcmonkey4eva** [comment]
See relevant commit for stabler fix ^
thanks though

**Comment by MelonCode** [comment]
Haha, Ok then. Good luck 
Just cus we already here, can you explain what is getTargetHelp() method returns? PlaceholderAPI string?

**Comment by mcmonkey4eva** [comment]
that returns a string if the integration has any custom targets, to quickly and shortly describe the target option.

Return an empty string if there's no custom targets.

**Comment by MelonCode** [comment]
What do you mean on "Custom target"?

**Comment by mcmonkey4eva** [comment]
A... target option added by integration...

**Pull request closed without merging**
